### ISSUE TITLE
Setting JOYENT_IMGADM_IDENTITY doesn't seem to work...

### ISSUE THREAD

**Issue by chorrell** [joyent/sdc-imgapi-cli#2]
I have the following in my .bashrc:

```
key="$HOME/.ssh/mu-chris.pub"
fp=$(ssh-keygen -E md5 -l -f "$key" | awk '{print $2}' | cut -d: -f2- 2> /dev/null)
if [[ $? -gt 0 ]]; then
    # OpenSSH version < 6.8
    fp=$(ssh-keygen -l -f "$key" | awk '{print $2}' | tr -d '\n')
fi

export JOYENT_IMGADM_USER=mu-chris
export JOYENT_IMGADM_IDENTITY=$fp
```

Running simple commands cause the following error:

```
[christopher@MacBook ~/.ssh]$ joyent-imgadm list

assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: key
    at Object.module.exports.(anonymous function) [as ok] (/usr/local/lib/node_modules/imgapi-cli/node_modules/assert-plus/assert.js:242:35)
    at Fingerprint.matches (/usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk/lib/fingerprint.js:51:9)
    at /usr/local/lib/node_modules/imgapi-cli/node_modules/smartdc-auth/lib/index.js:365:24
    at /usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk-agent/lib/client.js:80:3
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk-agent/lib/client.js:365:3)
    at EventEmitter.emit (events.js:95:17)
    at AgentDecodeStream.<anonymous> (/usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk-agent/lib/client.js:473:18)
    at AgentDecodeStream.emit (events.js:92:17)
    at emitReadable_ (/usr/local/lib/node_modules/imgapi-cli/node_modules/readable-stream/lib/_stream_readable.js:464:10)
    at emitReadable (/usr/local/lib/node_modules/imgapi-cli/node_modules/readable-stream/lib/_stream_readable.js:458:7)
```

What am I doing wrong?

**Comment by arekinath** [comment]
Can you run for me:
```shell
find /usr/local/lib/node_modules -type d -name sshpk -print -exec json -f {}/package.json version \;
```

**Comment by chorrell** [comment]
Sure!

```
[christopher@MacBook ~]$ find /usr/local/lib/node_modules -type d -name sshpk -print -exec json -f {}/package.json version \;
/usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk
1.3.0
/usr/local/lib/node_modules/imgapi-cli/node_modules/sshpk-agent/node_modules/sshpk
1.6.2
/usr/local/lib/node_modules/manta/node_modules/sshpk
1.4.4
/usr/local/lib/node_modules/sdc-clients/node_modules/sshpk
1.4.7
/usr/local/lib/node_modules/smartdc/node_modules/sshpk
1.4.7
/usr/local/lib/node_modules/triton/node_modules/http-signature/node_modules/sshpk
1.6.1
/usr/local/lib/node_modules/triton/node_modules/smartdc-auth/node_modules/sshpk
1.4.7
/usr/local/lib/node_modules/triton/node_modules/sshpk
1.4.4
```

**Comment by arekinath** [comment]
This looks like it was caused by PUBAPI-1163 not being carried over into this repo (the second copy of `sshpk` inside the `sshpk-agent` dir is a giveaway for this issue). I've pushed a patch for that this morning, would you mind deleting your `/usr/local/lib/node_modules/imgapi-cli` directory and re-installing it with `npm install`?

**Comment by chorrell** [comment]
Yep, that fixed it!
